### PR TITLE
test: 💍 add unit testing && coverage check using codecov

### LINKED ISSUE #4: [unit testing] Add coverage check using codecov
[unit testing] Add coverage check using CODEBEAT.
You have to write the tests & try to fix if any error occurs.
Refer - https://hub.codebeat.co/docs/test-coverage-reports#section-setting-up-for-javascript-typescript

coverage will only be calculated if previous tests are passed & it's in the master branch.

### PR DESCRIPTION
**Pull request by theashraf**
- [x] unit test memory.js 
- [x] add `test:coverage` npm script
- [x] report code coverage using `codeclimate-test-reporter` package
- [x] run `validate` npm script , on `pre-commit` hook using `husky` package
- [x] specify CODECLIMATE_REPO_TOKEN as an environment variable from travis build settings
Closes: #4

### CODE REVIEW

**Comment by unsuitable001** [comment]
Modify the `runcheckendline.sh` file to exclude the `node modules` directory to pass the Travis Test.
Excellent work. Thanks a lot.
Also rename `memory.test.js` to `memory.test.min.js` so, `codacy quality review` will not scan it.
@theashraf 

& Do `module.export` in `memory.js` only if it's a node environment. `memoryJS` is meant for browser and node both. To check if it's node environment, you can do something like, `if(window==null)` .

& Finally squash all commits into one :smile:

**Comment by theashraf** [comment]
@unsuitable001 Thank you for the review

### TODO
- [x] exclude `node_modules` from `runcheckendline.sh` 
- [x] module.exports `memoryJS` only in node env

### notes
- in order to make Travis build pass, you have to specify CODECLIMATE_REPO_TOKEN as an environment variable, kindly check the attached screenshot
Screenshot from 2019-10-14 19-57-01
- I didn't rename the `memory.test.js` file to `memory.test.min.js`, since it will not be run by `jest`, also it make sense to let `Codacy` scan the test files as well
- before merging, you can choose to `squash and merge` instead of just `merge` :smile:

**Comment by unsuitable001** [comment]
Thanks a lot for your valuable contribution @theashraf . I'm glad to have you here.

Please put the coverage report under `after script` & check if branch is `master` before executing it. Environment variable is only declared under the `master branch` scope.

And, the environment variables are not available for pull request ☹️.

See : https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

So, check that too. There's a env variable in Travis `TRAVIS_PULL_REQUEST` , if it's not a PR, then it returns false. If it's a PR, skip the coverage submission for now.

But, I'll be glad if you come up with a solution for that PR thing. Because, it's important to check a coverage of a PR.

I'm also finding a solution.

Everything else is great! & You are right about that `memory.test.js` thing.

**Comment by theashraf** [comment]
## TODO
- [x] move coverage report script under `after_script` 
- [x] report coverage only for `master` and `pull requests`
- [ ] set env variable CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage from Travis build settings as mentioned in https://hub.codebeat.co/docs/test-coverage-reports
## Notes
- i've created `report-coverage.sh` which will run the coverage report only on master and pull requests.
- `report-coverage.sh` will run under `after_success`
- @unsuitable001 don't forget to set env variable `CODECLIMATE_API_HOST` as mentioned in the TODO
- also, I think we should run the `runcheckendline.sh` in the `validate` npm script, this will help us see the result of the `runcheckendline` check before committing, also what do you think?

**Comment by unsuitable001** [comment]
@theashraf It's all set actually.
see:
Screenshot from 2019-10-16 10-09-52

But, the issue is, 
the environment variables are not available for pull request
See : https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

Can you suggest a way to report coverage for PRs as well?

**Comment by theashraf** [comment]
I think [codecov](https://codecov.io/) is a nice tool to integrate, check it out

**Comment by unsuitable001** [comment]
You mean, moving from codebeat to codecov?

**Comment by theashraf** [comment]
yes, it would be easier for me to integrate since I've used it before

**Comment by unsuitable001** [comment]
Ok. I'm setting it up ASAP. You can start working on it in this PR.

**Comment by unsuitable001** [comment]
Done @theashraf from my side!

**Comment by unsuitable001** [comment]
Well done!!!! I'll merge it soon.
If you are interested, you can also try looking at Pull #8  @theashraf 
We have to add test for that file too. I'll open the issue soon.
Though, it's not merged yet, it likely to be (after some modifications).

**Comment by theashraf** [comment]
Great, I think having a simple example like the one that you already created under the `examples` folder, is fine but if you would like to create a demo app, it would be better to create it in a separate repo and attach its URL to the `memoryJS` README.md for reference, this will make it easier to maintain both the demo and the source, @unsuitable001  what do you think ?

**Comment by unsuitable001** [comment]
@theashraf I am also thinking the same. Great work.

**Pull request merged**
