### PR TITLE
added package.json for npm package publishing

### PR DESCRIPTION
**Pull request by MitchMo**
This will get you started in the right direction to taking this and turning it into an NPM package, issue #1 . I've added the package.json file which is used by NPM to create the package. To actually publish the package, all you will have to do is run, `npm publish`, while you are inside the folder.

Some things to look at before publishing. In package.json, you have name, version, author, and description that you can edit with what you would like. I've added main and files as well into the JSON. Main tells NPM that memory.min.js will be the entry point into your package when someone references it by the package name. Files is there to tell NPM which files it should publish to the package. I added the two minified files, but can be updated to include the non-minified version as well. 

One other thing that can be done is referencing a file directly once the package is installed like so, 
```
const memoryJS = require('../node_modules/memory.min.js');
```
That is a pretty common way to reference pure JS files that were packaged to be used inside NodeJS or something like React or Angular. I hope this helps!

### CODE REVIEW

**Comment by unsuitable001** [comment]
Excellent @MitchMo !
Can you add `standard` to the `test` ? Refer - https://standardjs.com/


:smile:
You can put a :star2: & share.
I appreciate your efforts a lot.

**Comment by MitchMo** [comment]
Sure! I can get that added in right now

**Comment by MitchMo** [comment]
@unsuitable001 I've added standardJS to the test script to check memory.js. Initially I added it as a devDependency with, 
```
npm install standard --save-dev
```
But when I pushed the change, it failed the travis-ci check because standardJS failed while checking the node_modules folder. Since this is not your packages code, I removed it as a dependency. In order to use the test, standardJS will need to be installed globally, 
```
npm install standard --global
```
If you decide you would like it to be a package dependency, I've left in the .gitignore file to keep things clean. You will just need to add the following to your package.json file,
```
"devDependencies": {
    "standard": "^14.3.1"
  }
```

**Comment by unsuitable001** [comment]
Great work @MitchMo ! There's no need to add it as a dependency. :smile: . It's fine in your last commit. Can you please squash it to a single commit? So, it will be cleaner to maintain :smiley: .
Thanks a lot. I'll merge this tomorrow!

**Pull request merged**
